export const setFlag = (country) => {
	switch (country) {
		case "brazil":
			return require("./../images/flags/brazil.svg");
		case "france":
			return require("./../images/flags/france.svg");
		case "argentina":
			return require("./../images/flags/argentina.svg");
		case "england":
			return require("./../images/flags/england.svg");
		case "spain":
			return require("./../images/flags/spain.svg");
		case "germany":
			return require("./../images/flags/germany.svg");
		case "netherlands":
			return require("./../images/flags/netherlands.svg");
		case "belgium":
			return require("./../images/flags/belgium.svg");
		case "portugal":
			return require("./../images/flags/portugal.svg");
		case "denmark":
			return require("./../images/flags/denmark.svg");
		case "uruguay":
			return require("./../images/flags/uruguay.svg");
		case "croatia":
			return require("./../images/flags/croatia.svg");
		case "senegal":
			return require("./../images/flags/senegal.svg");
		case "serbia":
			return require("./../images/flags/serbia.svg");
		case "switzerland":
			return require("./../images/flags/switzerland.svg");
		case "ecuador":
			return require("./../images/flags/ecuador.svg");
		case "mexico":
			return require("./../images/flags/mexico.svg");
		case "poland":
			return require("./../images/flags/poland.svg");
		case "usa":
			return require("./../images/flags/usa.svg");
		case "wales":
			return require("./../images/flags/wales.svg");
		case "south-korea":
			return require("./../images/flags/south-korea.svg");
		case "cameroon":
			return require("./../images/flags/cameroon.svg");
		case "ghana":
			return require("./../images/flags/ghana.svg");
		case "iran":
			return require("./../images/flags/iran.svg");
		case "japan":
			return require("./../images/flags/japan.svg");
		case "morocco":
			return require("./../images/flags/morocco.svg");
		case "australia":
			return require("./../images/flags/australia.svg");
		case "canada":
			return require("./../images/flags/canada.svg");
		case "qatar":
			return require("./../images/flags/qatar.svg");
		case "tunisia":
			return require("./../images/flags/tunisia.svg");
		case "costa-rica":
			return require("./../images/flags/costa-rica.svg");
		case "saudi-arabia":
			return require("./../images/flags/saudi-arabia.svg");
	}
};
