export const setFlag = (country) => {
	switch (country) {
		case "argentina":
			return require("./../images/flags/argentina.svg");
		case "australia":
			return require("./../images/flags/australia.svg");
		case "belgium":
			return require("./../images/flags/belgium.svg");
		case "brazil":
			return require("./../images/flags/brazil.svg");
		case "colombia":
			return require("./../images/flags/colombia.svg");
		case "costa-rica":
			return require("./../images/flags/costa-rica.svg");
		case "croatia":
			return require("./../images/flags/croatia.svg");
		case "denmark":
			return require("./../images/flags/denmark.svg");
		case "egypt":
			return require("./../images/flags/egypt.svg");
		case "england":
			return require("./../images/flags/england.svg");
		case "france":
			return require("./../images/flags/france.svg");
		case "germany":
			return require("./../images/flags/germany.svg");
		case "iceland":
			return require("./../images/flags/iceland.svg");
		case "iran":
			return require("./../images/flags/iran.svg");
		case "japan":
			return require("./../images/flags/japan.svg");
		case "south-korea":
			return require("./../images/flags/south-korea.svg");
		case "mexico":
			return require("./../images/flags/mexico.svg");
		case "morocco":
			return require("./../images/flags/morocco.svg");
		case "nigeria":
			return require("./../images/flags/nigeria.svg");
		case "panama":
			return require("./../images/flags/panama.svg");
		case "peru":
			return require("./../images/flags/peru.svg");
		case "poland":
			return require("./../images/flags/poland.svg");
		case "portugal":
			return require("./../images/flags/portugal.svg");
		case "russia":
			return require("./../images/flags/russia.svg");
		case "saudi-arabia":
			return require("./../images/flags/saudi-arabia.svg");
		case "senegal":
			return require("./../images/flags/senegal.svg");
		case "serbia":
			return require("./../images/flags/serbia.svg");
		case "spain":
			return require("./../images/flags/spain.svg");
		case "sweden":
			return require("./../images/flags/sweden.svg");
		case "switzerland":
			return require("./../images/flags/switzerland.svg");
		case "tunisia":
			return require("./../images/flags/tunisia.svg");
		case "uruguay":
			return require("./../images/flags/uruguay.svg");
	}
};
