// Team list
// - [ranked by odds of winning, country, group country is in]
export const teams = [
	[12, "Russia", "A"],
	[32, "Saudi Arabia", "A"],
	[25, "Egypt", "A"],
	[10, "Uruguay", "A"],
	[8, "Portugal", "B"],
	[4, "Spain", "B"],
	[28, "Morocco", "B"],
	[27, "Iran", "B"],
	[3, "France", "C"],
	[23, "Australia", "C"],
	[18, "Peru", "C"],
	[17, "Denmark", "C"],
	[5, "Argentina", "D"],
	[20, "Iceland", "D"],
	[9, "Croatia", "D"],
	[22, "Nigeria", "D"],
	[2, "Brazil", "E"],
	[14, "Switzerland", "E"],
	[24, "Costa Rica", "E"],
	[21, "Serbia", "E"],
	[1, "Germany", "F"],
	[15, "Mexico", "F"],
	[16, "Sweden", "F"],
	[29, "South Korea", "F"],
	[6, "Belgium", "G"],
	[31, "Panama", "G"],
	[30, "Tunisia", "G"],
	[7, "England", "G"],
	[13, "Poland", "H"],
	[19, "Senegal", "H"],
	[11, "Colombia", "H"],
	[26, "Japan", "H"]
];
